### PR TITLE
Use identity component

### PR DESCRIPTION
**Pull request by davidlehn**

### CODE REVIEW

**Comment by dlongley** [comment]
This is the commit that previously added code to hide local identities that have no public fields:

https://github.com/digitalbazaar/bedrock-idp/commit/b9f5acb0198e16eb8e9ceb08af0eb9e79e628231

It also added tests that are not being removed by this PR.

I'm not sure as to the reasoning for either approach. I think hiding them may have been done to prevent exposing the DID associated with a local vanity URL? If so, this patch re-exposes that. I suppose an alternative patch could be to only expose a "private" identity if it is also a local one. But, again, I'm not sure about the reasoning either way. Any input on that?

**Comment by dlongley** [comment]
If we want to merge this now and deal with the issues raised above later, I'm fine with that.

**Comment by dlongley** [comment]
For DID-based identities, we should return 404 for private identities. For non-DID-based identities, we can return the base public information.

**Comment by lamara** [comment]
I think this is ok! As long as we make a note that the bedrock-idp services.identity.js should get torn down at some point.

**Comment by dlongley** [comment]
I'm ok with merging this.

**Pull request merged**
